language: script

sudo: required
services:
  - docker


branches:
  only:
    - master


install: true


script:
  # Build
  - docker build . -t feramhq/docker-service-frontail:latest
  - docker tag feramhq/docker-service-frontail:latest "feramhq/docker-service-frontail:$(git describe --always)"

  # Push to hub.docker.com
  - docker login -u feramhq -p "$DOCKER_HUB_PASSWORD"
  - docker push feramhq/docker-service-frontail
